server:
  port: 8360

spring:
  cloud:
    gateway:
      routes:
      - id: coreModule
        uri: http://localhost:3500/
        predicates:
        - Path=/**

app:
  service:
    core: http://localhost:3500/

