server:
  port: 8360

app:
  service:
    core: http://localhost:3500/

spring:
  cloud:
    gateway:
      routes:
      - id: coreModule
        uri: ${app.service.core}
        predicates:
        - Path=/**
